name: lint

on: ["push", "pull_request"]

jobs:
  lint:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ruff check
        run: |
          pipx run ruff check --diff msgpack/ test/ setup.py

      - name: ruff format
        run: |
          pipx run ruff format --diff msgpack/ test/ setup.py
