name: Build Linux Wheels
on:
  push:
  pull_request:
  create:

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Cythonize
        shell: bash
        run: |
          pip install -U pip
          pip -V
          pip install -r requirements.txt
          make cython
          #python setup.py sdist

      - name: Build wheels
        shell: bash
        run: |
          make linux-wheel

      - name: Install qemu-user-static for docker
        shell: bash
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build arm64 wheels
        shell: bash
        run: |
          make linux-arm64-wheel

      - name: Run test (3.8)
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: --no-index -f dist/wheelhouse
          pytest -v test


      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Run test (3.10)
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: --no-index -f dist/wheelhouse
          pytest -v test

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run test (3.9)
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: --no-index -f dist/wheelhouse
          pytest -v test

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Run test (3.7)
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: --no-index -f dist/wheelhouse
          pytest -v test

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Run test (3.6)
        run: |
          pip install pytest
          pip install -v msgpack --only-binary :all: --no-index -f dist/wheelhouse
          pytest -v test


      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: linux-wheels
          path: ./dist/wheelhouse/
