name: Build and test windows wheels
on:
  push:
  pull_request:
  create:

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cythonize
        shell: bash
        run: |
          pip install -U Cython
          make cython
          #python setup.py sdist

      - name: Python 3.6 (amd64)
        env:
          PYTHON: "py -3.6-64"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.6 (x86)
        env:
          PYTHON: "py -3.6-32"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.7 (amd64)
        env:
          PYTHON: "py -3.7-64"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.7 (x86)
        env:
          PYTHON: "py -3.7-32"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.8 (amd64)
        env:
          PYTHON: "py -3.8-64"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.8 (x86)
        env:
          PYTHON: "py -3.8-32"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.9 (amd64)
        env:
          PYTHON: "py -3.9-64"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.9 (x86)
        env:
          PYTHON: "py -3.9-32"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.10 (amd64)
        env:
          PYTHON: "py -3.10-64"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Python 3.10 (x86)
        env:
          PYTHON: "py -3.10-32"
        shell: bash
        run: |
          ci/runtests.sh

      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: win-wheels
          path: ./dist
