name: Build and test windows wheels
on:
  push:
    branches:
      - master
      - test
  pull_request:
  create:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cythonize
        shell: bash
        run: |
          pip install -U Cython
          make cython
          #python setup.py sdist

      - name: Python 3.6 (amd64)
        env:
          PYTHON: "py -3.6-64"
        shell: bash
        run: &testscript |
          ${PYTHON} -VV
          ${PYTHON} -m pip install setuptools wheel pytest
          ${PYTHON} setup.py build_ext -if
          ${PYTHON} -c "from msgpack import _cmsgpack"
          ${PYTHON} setup.py bdist_wheel
          ${PYTHON} -m pytest -v test

      - name: Python 3.6 (x86)
        env:
          PYTHON: "py -3.6-32"
        shell: bash
        run: *testscript

      - name: Python 3.7 (amd64)
        env:
          PYTHON: "py -3.7-64"
        shell: bash
        run: *testscript

      - name: Python 3.7 (x86)
        env:
          PYTHON: "py -3.7-32"
        shell: bash
        run: *testscript

      - name: Python 3.8 (amd64)
        env:
          PYTHON: "py -3.8-64"
        shell: bash
        run: *testscript

      - name: Python 3.8 (x86)
        env:
          PYTHON: "py -3.8-32"
        shell: bash
        run: *testscript

      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: win-wheels
          path: ./dist
