name: Build and test windows wheels
on:
  push:
  pull_request:
  create:

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cythonize
        shell: bash
        run: |
          pip install -U Cython
          make cython
          #python setup.py sdist

      - name: Build wheels
        shell: bash
        env:
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest {package}/test"
        run: |
          python -m pip install cibuildwheel
          python -m cibuildwheel

      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: win-wheels
          path: wheelhouse
